input:
  file: data/Haltetremor_aligned_dataset.h5
  imu: hand  # hand, forearm, upperarm

signal:
  axis: mag # x, y, z, mag
  sampling_rate: 120  # Hz

filter:
  lowcut: 2.0
  highcut: 12.0
  order: 2

analysis:
  method: both     # fft, cwt, both

cwt:
  min_frequency: 2
  max_frequency: 6

fft:
  nfft: 2 ** 10

output:
  save_figures: true
  directory: results