input:
  file: collected_datasets/Haltetremor_aligned_dataset.h5
  imu: right_forearm # left_hand, left_forearm, left_upperarm, right_hand, right_forearm, right_upperarm

signal:
  axis: z # x, y, z, mag
  sampling_rate: 120  # Hz

filter:
  lowcut: 2.0
  highcut: 12.0
  order: 2

analysis:
  method: both     # fft, cwt, both

cwt:
  min_frequency: 2
  max_frequency: 8
  start_time: 0
  end_time: 35

fft:
  nfft: 1024

output:
  save_figures: False
  save_videos: False
  directory: results

